<a href="https://colab.research.google.com/github/2403a52078-art/AIAC/blob/main/lab_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

task1:Use Gemini in Colab to write a function that filters out all negative numbers from a
given list.

Now you can copy and paste the generated function code into a new code cell and test it.

In [2]:
def filter_negative_numbers(input_list):
  """
  Filters out all negative numbers from a given list.

  Args:
    input_list: A list of numbers.

  Returns:
    A new list containing only the non-negative numbers from the input list.
  """
  return [number for number in input_list if number >= 0]

# Example usage:
my_list = [1, -2, 3, -4, 5, 0, -6]
filtered_list = filter_negative_numbers(my_list)
print(filtered_list)

[1, 3, 5, 0]


The code defines a function called filter_negative_numbers that takes a list of numbers as input. It uses a list comprehension [number for number in input_list if number >= 0] to iterate through the input list and create a new list containing only the numbers that are greater than or equal to 0 (i.e., non-negative numbers). Finally, it returns this new list. The example usage demonstrates how to call the function and print the resulting filtered list.

task2:Ask Gemini to generate code that reads a text file and counts the frequency of each
word

You can copy and paste the generated code into a new cell and test it. Remember to replace `"your_text_file.txt"` with the actual path to your text file.

In [4]:
import re
from collections import Counter

def count_word_frequency(filepath):
  """
  Reads a text file and counts the frequency of each word.

  Args:
    filepath: The path to the text file.

  Returns:
    A dictionary where keys are words and values are their frequencies.
  """
  try:
    with open(filepath, 'r', encoding='utf-8') as file:
      text = file.read().lower()
      # Use regex to find words (alphanumeric sequences)
      words = re.findall(r'\b\w+\b', text)
      word_counts = Counter(words)
      return word_counts
  except FileNotFoundError:
    print(f"Error: File not found at {filepath}")
    return None
  except Exception as e:
    print(f"An error occurred: {e}")
    return None

# Example usage:
# Create a dummy text file for testing
with open("sample_text_file.txt", "w") as f:
    f.write("This is a sample text file. This file is for testing the word frequency counter.")

file_path = "sample_text_file.txt"
word_frequencies = count_word_frequency(file_path)

if word_frequencies:
  # Print the word frequencies (you can adjust how many to print)
  for word, count in word_frequencies.most_common(10): # Print top 10 most common words
    print(f"{word}: {count}")

this: 2
is: 2
file: 2
a: 1
sample: 1
text: 1
for: 1
testing: 1
the: 1
word: 1


This code defines a function count_word_frequency that takes a file path as input.

It opens the specified text file, reads its content, and converts it to lowercase.
It then uses a regular expression \b\w+\b to find all words (sequences of alphanumeric characters) in the text.
It uses the Counter object from the collections module to count the frequency of each word.
The function returns a dictionary where keys are words and values are their frequencies.
The example usage section first creates a dummy text file named "sample_text_file.txt" for testing.
It then calls the count_word_frequency function with the path to the dummy file.
Finally, if the function returns word frequencies, it prints the top 10 most common words and their counts.


task3: Use Cursor AI to generate a Python class called Book with attributes title, author, and
a method summary() that prints the details.

In [5]:
class Book:
  """
  Represents a book with a title and author.
  """
  def __init__(self, title, author):
    """
    Initializes a new Book instance.

    Args:
      title: The title of the book.
      author: The author of the book.
    """
    self.title = title
    self.author = author

  def summary(self):
    """
    Prints the details of the book (title and author).
    """
    print(f"Title: {self.title}")
    print(f"Author: {self.author}")

# Example usage:
my_book = Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams")
my_book.summary()

Title: The Hitchhiker's Guide to the Galaxy
Author: Douglas Adams


This code defines a Python class named Book.

The __init__ method is the constructor. It's called when you create a new Book object. It takes title and author as arguments and stores them as attributes of the object using self.title = title and self.author = author.
The summary() method is defined within the Book class. When called on a Book object, it prints the title and author of that specific book using an f-string for formatted output.
The example usage at the end creates an instance of the Book class called my_book with a specific title and author, and then calls the summary() method on my_book to print its details.


task4:Ask Gemini to write a program that checks whether a number is an Armstrong
number, and then modify it using Cursor AI to improve performance or structure.

Here is the code generated by Gemini. You can copy and paste it into a new code cell and test it.

In [13]:
def is_armstrong_number(number):
  """
  Checks if a number is an Armstrong number.

  An Armstrong number (or narcissistic number) is a number that is the sum
  of its own digits each raised to the power of the number of digits.
  For example, 153 is an Armstrong number because 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153.
  """
  # Convert the number to a string to easily access digits
  number_str = str(number)
  num_digits = len(number_str)
  sum_of_powers = 0

  # Calculate the sum of digits raised to the power of the number of digits
  for digit in number_str:
    sum_of_powers += int(digit) ** num_digits

  # Check if the sum of powers equals the original number
  return sum_of_powers == number

# Example usage:
num_to_check = 153
if is_armstrong_number(num_to_check):
  print(f"{num_to_check} is an Armstrong number.")
else:
  print(f"{num_to_check} is not an Armstrong number.")

num_to_check = 123
if is_armstrong_number(num_to_check):
  print(f"{num_to_check} is an Armstrong number.")
else:
  print(f"{num_to_check} is not an Armstrong number.")

153 is an Armstrong number.
123 is not an Armstrong number.


This code defines a function called is_armstrong_number that checks if a given integer is an Armstrong number.

It first converts the input number to a string (number_str) to easily access its individual digits.
It calculates the number of digits in the number (num_digits).
It initializes a variable sum_of_powers to 0.
It then iterates through each digit in the number_str.
For each digit, it converts it back to an integer (int(digit)) and raises it to the power of the total number of digits (num_digits). This result is added to sum_of_powers.
Finally, it compares the calculated sum_of_powers with the original number. If they are equal, the function returns True, indicating it's an Armstrong number; otherwise, it returns False.
The example usage shows how to call the function with two different numbers (153 and 123) and prints whether each is an Armstrong number.


task5:Use both Gemini and Cursor AI to generate code for sorting a list of dictionaries by a
specific key (e.g., age).

Here is the code generated by Gemini. You can copy and paste it into a new code cell and test it.

In [17]:
def sort_list_of_dictionaries(list_of_dicts, sort_key):
  """
  Sorts a list of dictionaries by a specific key.

  Args:
    list_of_dicts: The list of dictionaries to sort.
    sort_key: The key to sort the dictionaries by.

  Returns:
    A new list of dictionaries sorted by the specified key.
  """
  return sorted(list_of_dicts, key=lambda x: x.get(sort_key))

# Example usage:
data = [
    {'name': 'Alice', 'age': 30, 'city': 'New York'},
    {'name': 'Bob', 'age': 25, 'city': 'London'},
    {'name': 'Charlie', 'age': 35, 'city': 'Paris'},
    {'name': 'David', 'age': 25, 'city': 'Tokyo'},
]

sorted_data = sort_list_of_dictionaries(data, 'age')
print("Sorted by age:")
print(sorted_data)

sorted_data_name = sort_list_of_dictionaries(data, 'name')
print("\nSorted by name:")
print(sorted_data_name)

Sorted by age:
[{'name': 'Bob', 'age': 25, 'city': 'London'}, {'name': 'David', 'age': 25, 'city': 'Tokyo'}, {'name': 'Alice', 'age': 30, 'city': 'New York'}, {'name': 'Charlie', 'age': 35, 'city': 'Paris'}]

Sorted by name:
[{'name': 'Alice', 'age': 30, 'city': 'New York'}, {'name': 'Bob', 'age': 25, 'city': 'London'}, {'name': 'Charlie', 'age': 35, 'city': 'Paris'}, {'name': 'David', 'age': 25, 'city': 'Tokyo'}]


This code defines a function called sort_list_of_dictionaries that takes a list of dictionaries and a sort_key (the key to sort by) as input.

It uses the built-in Python sorted() function to sort the list of dictionaries.
The key=lambda x: x.get(sort_key) part is crucial. It tells the sorted() function to use the value associated with the sort_key in each dictionary (x) as the basis for sorting. The lambda function is a small anonymous function that takes a dictionary x and returns the value of x at the specified sort_key using x.get(sort_key). Using .get() is a safe way to access the key's value, returning None if the key doesn't exist, which prevents errors.
The function returns a new sorted list of dictionaries.
The example usage demonstrates sorting the sample data list first by 'age' and then by 'name', printing the results.